#!/bin/bash

app=$1
new_users=$2

if [[ "scm" = "$app" ]];

then
    sudo service tomcat7 stop
    echo $new_users | grep -q ","
    if [[ $? -eq 0 ]];
    then

 for user in $(echo "$new_users" | sed "s/,/ /g")
        do
            YNH_ADMIN=false
YNH_DATE=$(date +%s%N | cut -b1-13)
YNH_DISPLAYNAME=$(sudo yunohost user info $user | grep "fullname: " | sed s/'fullname: '/''/g)
YNH_MAIL=$(sudo yunohost user info $user | grep "mail: " | sed s/'mail: '/''/g)
YNH_LOGIN=$user
YNH_PASSWORD=$(echo -n $passwd | sha1sum | sed s/'  -'/''/g)
        done

else
        
    fi
    sudo service tomcat7 start
fi