#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3


# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong user"
    exit 1
fi


sudo yunohost app setting scmmanager admin_user -v $user

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a scmmanager
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


# add the scm-manager repository
echo 'deb http://maven.scm-manager.org/nexus/content/repositories/releases ./' > /etc/apt/sources.list.d/scmmanager.conf

# install gpg key for the scm-manager repository
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com D742B261

# update
sudo apt-get update

# install scm-server
sudo apt-get install scm-server

# Copy files to the right place
final_path=/opt/scmmanager
data_path=/home/yunohost.app/scmmanager
sudo mkdir -p $data_path

# Install SCM-Manager

# Copy files to the right place

# Change variables in SCM-Manager configuration
# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/scmmanager.conf




sudo chown scm:scm $data_path
sudo chmod 755 /home/yunohost.app
sudo find $final_path -type f | xargs sudo chmod 664
sudo find $final_path -type d | xargs sudo chmod 775
sudo chmod -R 770 $data_path


sudo service scm-server start

# Add scm-server service to YunoHost's monitoring
sudo yunohost service add scm-server --log /var/log/scm-server/ --status "ps aux | grep scm-server | grep -v grep"


# Reload Nginx and regenerate SSOwat conf

sudo service scm-server restart
sudo service nginx reload
sudo yunohost app ssowatconf

