#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3
admin_passwd=$4

SCMMANAGERAPPFILE="scm-webapp-1.40.war"

SCMMANAGERAUTOLOGIN="scm-autologin-plugin-1.0.zip"


# Check if admin password is not null
if [ "$admin_passwd" = "" ]; then
echo "Wrong password"
    exit 1
fi

# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong user"
    exit 1
fi


sudo yunohost app setting scmmanager admin_user -v $user

# Check domain/path availability

sudo yunohost app checkurl $domain$path -a scm
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


# Install dependencies
sudo apt-get install -y git subversion 
sudo apt-get install -y openjdk-7-jre default-jre-headless tomcat7 

sudo service tomcat7 stop
sudo cp ../sources/$SCMMANAGERAPPFILE /var/lib/tomcat7/webapps/scm.war
sudo chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/

data_path=/home/yunohost.app/scm

# Copy files to the right place

sudo mkdir -p $data_path
sudo chown -hR tomcat7:tomcat7 $data_path
sudo chmod 775 $data_path

sudo service tomcat7 start
sleep 20
wget http://localhost:8080/scm/ 
rm index.html
sudo service tomcat7 stop
# Change variables in SCM-Manager configuration

sudo unzip ../sources/$SCMMANAGERAUTOLOGIN -d $data_path
sudo chown -hR tomcat7:tomcat7 $data_path
sudo chmod 775 $data_path

sudo sh -c "echo 'scm.home = /home/yunohost.app/scm' >> /var/lib/tomcat7/webapps/scm/WEB-INF/classes/scm.properties"
sudo cp ../conf/autoLogin.xml /home/yunohost.app/scm/config/autoLogin.xml
sudo cp ../conf/classpath.xml /home/yunohost.app/scm/config/classpath.xml

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$path.conf


#Add admin user
YNH_ADMIN=true
YNH_DATE=$(date +%s%N | cut -b1-13)
YNH_DISPLAYNAME=$(sudo yunohost user info $user | grep "fullname: " | sed s/'fullname: '/''/g)
YNH_MAIL=$(sudo yunohost user info $user | grep "mail: " | sed s/'mail: '/''/g)
YNH_LOGIN=$user
YNH_PASSWORD=$(echo -n $admin_passwd | sha1sum | sed s/'  -'/''/g)


sudo sed -i "s/YNH_ADMIN/$YNH_ADMIN/g" ../conf/user.conf
sudo sed -i "s/YNH_DATE/$YNH_DATE/g" ../conf/user.conf
sudo sed -i "s/YNH_DISPLAYNAME/$YNH_DISPLAYNAME/g" ../conf/user.conf
sudo sed -i "s/YNH_MAIL/$YNH_MAIL/g" ../conf/user.conf
sudo sed -i "s/YNH_LOGIN/$YNH_LOGIN/g" ../conf/user.conf
sudo sed -i "s/YNH_PASSWORD/$YNH_PASSWORD/g" ../conf/user.conf

sudo sed -i "s/'</users>'/''/g" /home/yunohost.app/scm/config/users.xml


sudo service tomcat7 restart

sudo yunohost app setting scm skipped_uris -v "/svn,/git,/hg"

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
