#!/bin/bash

domain=$(sudo yunohost app setting scmmanager domain)
sudo service scm-server stop
sudo killall scm-server
sudo update-rc.d scm-server disable

sudo rm -f /etc/nginx/conf.d/$domain.d/scmmanager.conf
sudo rm -rf /etc/default/scm-server
sudo rm -rf /var/log/scmmanager
sudo rm -rf /tmp/scmmanager*

sudo yunohost service remove scmmanager
sudo service nginx reload
