#!/bin/bash

domain=$(sudo yunohost app setting scmmanager domain)
sudo service tomcat7 stop
sudo rm /var/lib/tomcat7/webapps/scm.war

sudo rm -f /etc/nginx/conf.d/$domain.d/scm.conf

sudo service tomcat7 start


sudo service nginx reload
